name: brainhack
channels:
  - conda-forge
dependencies:
  - h5py==2.9.0
  - matplotlib==3.1.0
  - xarray==0.12.1
  - numba==0.43.1
  - scikit-image==0.15.0
  - s3fs==0.3.4
  - zarr==2.3.1
  - seaborn==0.9.0
  - holoviews==1.12.3
  - datashader==0.7.0
  - hvplot==0.4.0
  - panel==0.5.1
  - tqdm==4.32.1
  - plotly==3.9.0
  - ipywidgets==7.4.2
  - intake==0.5.1
  - prefect==0.6.3
  - awscli==1.16.249
  - pip==19.2.3
  - python-graphviz
  - jupyterlab==1.1.2
  - jupyterhub==1.0.0
  - dask==2.7.0
  - scikit-learn==0.21.3
  - pip:
    - allensdk==1.1.1
    - neuroglia==0.1.0
    - neurodsp==2.0.0